# Generated by Django 5.0.14 on 2026-07-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='business.business'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
