# Generated by Django 5.0.14 on 2026-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services this code applies to. Leave empty to apply to all services.', related_name='promo_codes', to='services.service'),
        ),
    ]
