# Generated by Django 5.0.14 on 2026-07-21 09:49

import django.db.models.deletion
from django.db import migrations, models

BUSINESS_QUERY = "SELECT id FROM business_business WHERE is_active = 1 ORDER BY id LIMIT 1"


def populate_business(apps, schema_editor):
    business_id = None
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(BUSINESS_QUERY)
        row = cursor.fetchone()
        if row:
            business_id = row[0]

    if business_id is None:
        return

    models_to_update = [
        "LoyaltyRedemption",
        "LoyaltyReward",
        "PromoCode",
        "PromoRedemption",
        "Review",
        "SupportMessage",
    ]
    for model_name in models_to_update:
        Model = apps.get_model("engagement", model_name)
        Model.objects.filter(business__isnull=True).update(business_id=business_id)


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_seed_bloom_studio'),
        ('engagement', '0003_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyredemption',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_redemptions', to='business.business'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='business.business'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_codes', to='business.business'),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_promo_redemptions', to='business.business'),
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='business.business'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='business.business'),
        ),
        migrations.RunPython(populate_business, migrations.RunPython.noop),
    ]
