# Generated by Django 5.0.14 on 2026-07-21 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('business_type', models.CharField(choices=[('beauty_salon', 'Beauty Salon'), ('massage', 'Massage Center'), ('clinic', 'Clinic'), ('consultant', 'Consultant'), ('coach', 'Coach'), ('repair_shop', 'Repair Shop'), ('wellness', 'Wellness Center'), ('other', 'Other')], default='other', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30)),
                ('minimum_booking_notice_minutes', models.PositiveIntegerField(default=60)),
                ('maximum_advance_booking_days', models.PositiveIntegerField(default=60)),
                ('cancellation_window_hours', models.PositiveIntegerField(default=24)),
                ('default_buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('default_buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('require_manual_confirmation', models.BooleanField(default=True)),
                ('loyalty_enabled', models.BooleanField(default=False)),
                ('ai_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'business settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'business memberships',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'business')},
            },
        ),
    ]
