# Generated by Django 5.0.14 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
