# Generated by Django 5.0.14 on 2026-07-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_points_earned'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business'),
        ),
    ]
