# Generated by Django 5.0.14 on 2026-07-21 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Change'), ('reschedule', 'Reschedule'), ('created', 'Created'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=12)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=12)),
                ('old_start', models.DateTimeField(blank=True, null=True)),
                ('old_end', models.DateTimeField(blank=True, null=True)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'appointment audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
